# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tool monkey
description: adventures of an unfrozen caveman programmer

url: "http://erikerlandson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/blog/:year/:month/:day/:title/"

email: erikerlandson@yahoo.com
twitter_username: manyangled
github_username:  erikerlandson

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# installation:
# $ sudo dnf install ruby ruby-devel
# $ sudo dnf install @development-tools
# $ sudo dnf install @rpm-development-tools

# configure bundling dir
# $ cd /path/to/toolmonkey
# $ rm -rf .bundle vendor
# possibly also rm Gemfile.lock?
# $ bundle config set path 'vendor/bundle'
# $ bundle install

# jekyll-compose
# https://github.com/jekyll/jekyll-compose
# bundle exec jekyll help
# bundle exec jekyll post "post title"
# bundle exec jekyll serve
jekyll_compose:
  draft_default_front_matter:
    tags:
  post_default_front_matter:
    tags:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
